spring:
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
  datasource:
    name: leonds
    url: jdbc:mysql://localhost:3306/leonds?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 30000
    type: com.zaxxer.hikari.HikariDataSource
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: leonds
  http:
    encoding:
      charset: utf-8
      force: true
  messages:
    basename: i18n.messages
  cache:
    type: ehcache
  servlet:
    multipart:
      max-file-size: 10485760
server:
  port: 8000

debug: true
logging:
  level:
    root: debug
    com.leonds: debug
  file: D:\logs\leonds\leonds.log
app:
  file-location: D:\data\files\
  git:
    remote: https://github.com/leondss/articles.git
    local: D:\data\articles
  jwt:
    header: Leonds-Auth-Token
    secret: 1234eresdf56dfsdfsd#www.leonds.com@1223wkl#7890!@#$%^&*()/.,'][;