spring:
  thymeleaf:
    cache: false
  datasource:
    name: leonds
    url: jdbc:mysql://localhost:3306/leonds?useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: RootRoot#001
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: leonds
  http:
    encoding:
      charset: utf-8
      force: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  messages:
    basename: i18n.messages
server:
  port: 8000
debug: true
logging:
  level:
    root: debug
    com.leonds: debug
  file: D:\logs\leonds\leonds.log
shiro:
  loginUrl: /api/error/401
